export const appRoutePaths = {
  home: "/",
  login: "/login",
  userMetrics: "/user-metrics",
  financeMetrics: "/finance-metrics",
  financeMetricsTransactionHistory: "/finance-metrics/transaction-history",
  financeMetricsTaxReport: "/finance-metrics/tax-report",
  financeMetricsScheduledRenewal: "/finance-metrics/scheduled-renewal",
  trainingSessions: "/training-sessions",
  salesMetrics: "/sales-metrics",
  itAuditMetrics: "/it-audit-metrics",
  settings: "/settings",
  reports: "/reports",
  notifications: "/notifications",
  notFound: "*",
};
