export const appRoutePaths = {
  home: "/",
  login: "/login",
  userMetrics: "/user-metrics",
  financeMetrics: "/finance-metrics",
  financeMetricsTransactionHistory: "/finance-metrics/transaction-history",
  financeMetricsTaxReport: "/finance-metrics/tax-report",
  financeMetricsScheduledRenewal: "/finance-metrics/scheduled-renewal",
  trainingSessions: "/training-sessions",
  salesMetrics: "/sales-metrics",
  itAuditMetrics: "/it-audit-metrics",
  settings: "/settings",
  settingsRolesAndPermissions: "/settings/roles-and-permissions",
  rolePermissions: (id?: number) => ({
    format: `/role/:id/permissions/`,
    path: `/role/${id}/permissions/`,
  }),
  settingsUsers: "/settings/users",
  settingsPrices: "/settings/prices",
  settingsDiscounts: "/settings/discounts",
  settingsDiscountsSpecific: "/settings/discounts/specific",
  reports: "/reports",
  notifications: "/notifications",
  notFound: "*",
};
